-- Esquema principal de la base de datos ferreteria_maytro
-- Sección: Cotizaciones (COTIZACION y COTIZACION_DETALLES)
-- Nota: ejecute este bloque para añadir soporte de cotizaciones.

-- Cabecera de Cotización
CREATE TABLE IF NOT EXISTS COTIZACION (
  ID_COTIZACION VARCHAR(24) PRIMARY KEY,
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_VENCIMIENTO DATE NOT NULL,
  SUBTOTAL DECIMAL(12,2) NOT NULL DEFAULT 0,
  DESCUENTO DECIMAL(12,2) NOT NULL DEFAULT 0,
  TOTAL DECIMAL(12,2) NOT NULL DEFAULT 0,
  ESTADO ENUM('activa','expirada','cancelada','procesada') NOT NULL DEFAULT 'activa',
  ID_CLIENTES INT NULL,
  ID_SUCURSAL VARCHAR(10) NULL,
  ID_USUARIO INT NULL,
  NOTAS TEXT NULL,
  CONSTRAINT fk_cotizacion_cliente FOREIGN KEY (ID_CLIENTES) REFERENCES CLIENTES(ID_CLIENTES),
  CONSTRAINT fk_cotizacion_sucursal FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL),
  CONSTRAINT fk_cotizacion_usuario FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Detalles de Cotización
CREATE TABLE IF NOT EXISTS COTIZACION_DETALLES (
  ID_DETALLE_COTIZACION INT AUTO_INCREMENT PRIMARY KEY,
  ID_COTIZACION VARCHAR(24) NOT NULL,
  ID_PRODUCT INT NULL,
  AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0,
  PRECIO_UNIT DECIMAL(12,2) NOT NULL DEFAULT 0,
  SUB_TOTAL DECIMAL(12,2) NOT NULL DEFAULT 0,
  CONSTRAINT fk_det_cotizacion FOREIGN KEY (ID_COTIZACION) REFERENCES COTIZACION(ID_COTIZACION) ON DELETE CASCADE,
  CONSTRAINT fk_det_prod FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTOS(ID_PRODUCT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Índices auxiliares
CREATE INDEX idx_cotizacion_cliente ON COTIZACION(ID_CLIENTES);
CREATE INDEX idx_cotizacion_sucursal ON COTIZACION(ID_SUCURSAL);
CREATE INDEX idx_det_cotizacion ON COTIZACION_DETALLES(ID_COTIZACION);
